export const CUSTOMER_LIST_REQUEST = "CUSTOMER_LIST_REQUEST"
export const CUSTOMER_LIST_SUCCESS = "CUSTOMER_LIST_SUCCESS"
export const CUSTOMER_LIST_FAILED = "CUSTOMER_LIST_FAILED"

export const CUSTOMER_DETAIL_REQUEST = "CUSTOMER_DETAIL_REQUEST"
export const CUSTOMER_DETAIL_SUCCESS = "CUSTOMER_DETAIL_SUCCESS"
export const CUSTOMER_DETAIL_FAILED = "CUSTOMER_DETAIL_FAILED"

export const CUSTOMER_ORDER_LIST_REQUEST = "CUSTOMER_ORDER_LIST_REQUEST"
export const CUSTOMER_ORDER_LIST_SUCCESS = "CUSTOMER_ORDER_LIST_SUCCESS"
export const CUSTOMER_ORDER_LIST_FAILED = "CUSTOMER_ORDER_LIST_FAILED"