export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAILED = "ORDER_LIST_FAILED"

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_SUCCESS = "ORDER_DETAIL_SUCCESS"
export const ORDER_DETAIL_FAILED = "ORDER_DETAIL_FAILED"

export const PAYMENT_LIST_REQUEST = "PAYMENT_LIST_REQUEST"
export const PAYMENT_LIST_SUCCESS = "PAYMENT_LIST_SUCCESS"
export const PAYMENT_LIST_FAILED = "PAYMENT_LIST_FAILED"